### ISSUE TITLE
Connect-UI doesn't seem to be working

### ISSUE THREAD

**Issue by PrithivirajDamodaran** [Landoop/kafka-connect-ui#11]
I am running Kafka, connect and ZK in Mac OSX.  I tried running the below

```
docker run --rm -it -p 8000:8000 \
>            -e "CONNECT_URL=http://connect.distributed.url" \
>            landoop/kafka-connect-ui
Unable to find image 'landoop/kafka-connect-ui:latest' locally
latest: Pulling from landoop/kafka-connect-ui

3690ec4760f9: Already exists
7650bdbef93c: Pull complete
fb0f52d6cb77: Pull complete
04974ce5c127: Pull complete
450859f253ef: Pull complete
ff9e1d072f6d: Pull complete
Digest: sha256:fc74fd346133f58155f5362f0b2c75d6fe176895c7fb05021f0d6178be3243c4
Status: Downloaded newer image for landoop/kafka-connect-ui:latest

Enabling proxy because Connect doesn't send CORS headers yet.

Activating privacy features... done.
http://0.0.0.0:8000

```

I visited the http://0.0.0.0:8000 and this is what I saw. What am I missing ? Pls advice

<img width="1280" alt="screen shot 2016-12-21 at 3 48 35 pm" src="https://cloud.githubusercontent.com/assets/7071019/21385574/044b9dfa-c795-11e6-8bd9-19a2e4f5680a.png">

**Comment by jocelyndrean** [comment]
@PrithivirajDamodaran Got the same error here. Also on Mac OSX.

**Comment by andmarios** [comment]
One possible error point could be connect's url. You should use your computer's IP address and not localhost.

For example the IP of my laptop in my home network is `192.168.5.65`. Thus I would use for `CONNECT_URL` a value of `http://192.168.5.65:8083`.

Another possible error alongside this would be that you've setup docker so that containers can't access the ports of your OS —so for example in my case above, docker wouldn't be able to access 192.168.5.65.

If you can't make the docker image work, maybe we could give you some simple instructions on how to run a webserver instead, serving kafka-connect-ui and proxying connect distributed rest port (due to CORS).

**Comment by PrithivirajDamodaran** [comment]
Yeah changing localhost to IP fixed it, Thanks

**Comment by Antwnis** [comment]
@PrithivirajDamodaran if u like this project - please **star** it on github

**Comment by PrithivirajDamodaran** [comment]
Sure, I discovered this project accidentally when I almost rolledup my sleeves to build an UI for this ;-)

**Comment by Antwnis** [comment]
Cool - if u think there are some missing features - feel free to ask for them !

I hope u also enjoy our other UIs for Kafka on https://github.com/Landoop
