### ISSUE TITLE
Deployed docker image doesn't work

### ISSUE THREAD

**Issue by simplesteph** [Landoop/kafka-connect-ui#13]
I deployed the docker image (latest) in AWS and getting the following error:
![image](https://cloud.githubusercontent.com/assets/20851561/21754947/74dbc8ec-d65e-11e6-8deb-56503cef7c96.png)
My `CONNECT_URL` env variable is `http://kafka-connect-dev:8083/`

If I look into the docker container, I got the following:
```
/kafka-connect-ui # cat env.js 
var clusters = [
   {
     NAME: "default",
     KAFKA_CONNECT: "/api/kafka-connect"
   }
]
```

```
# cat /caddy/Caddyfile 
0.0.0.0:8000
tls off

root /kafka-connect-ui
log /access.log
proxy /api/kafka-connect http://kafka-connect-dev:8083 {
    without /api/kafka-connect
}
```

And connectivity exists from the box to the service:
```
$ nc -z kafka-connect-dev 8083
Connection to kafka-connect-dev 8083 port [tcp/us-srv] succeeded!
```

I also don't know where to look to see app logs

**Comment by andmarios** [comment]
Hello, thanks for the report.

It seems that your docker container is configured properly.

I would check for connectivity from the container to the service. Running this inside the container should return your Connect version:
```
apk add --no-cache curl
curl kafka-connect-dev:8083
````

A special case would be if for `kafka-connect-dev` you use localhost. This won't work because for the container, localhost is itself. You may replace it with your server's IP address (e.g 172.x.x.x).

The app logs are actually inside your browser, for example on Chrome open the developer's console. The server's logs inside the container are at `/access.log`.

**Comment by simplesteph** [comment]
```# curl http://kafka-connect-dev:8083/
{"version":"0.10.1.0-cp2","commit":"beb290796c342e22"}```

Connectivity exists from within the box

**Comment by simplesteph** [comment]
Sorry now it seems to work... might have been something about resolving DNS on time.... all good I'll close for now

**Comment by andmarios** [comment]
Glad it worked out! Feel free to re-open if needed.
