### ISSUE TITLE
Docker image isn't intuitive with multiple connect UI

### ISSUE THREAD

**Issue by simplesteph** [Landoop/kafka-connect-ui#43]
When referencing `my.1st.url,my.2nd.url,my.3rd.url` etc... The docker image works
But the problem is that the clusters are named generically and we lose the information about the URL endpoint. We either need to capability to override name or not lose the URL in the first place

![image](https://user-images.githubusercontent.com/20851561/27163126-b134aa30-51c8-11e7-82e0-191b669fa8d9.png)

This is due to what's happening here:
https://github.com/Landoop/kafka-connect-ui/blob/master/docker/run.sh#L39

**Comment by andmarios** [comment]
Noted. I can't promise it will be fixed soon, but it is a good idea to do something about it.

**Comment by simplesteph** [comment]
@andmarios proposed a very simple PR to solve this. Hopefully it works for you guys

**Comment by andmarios** [comment]
This looks like a simple and clean solution! Thanks, I'll give it a try tomorrow and probably merge it.

In the long term, I would also like to provide a way to set the name. Since Connect 3.2.x added the ability to provide CORS itself, we should add the `PROXY` option to this docker as well, which means that the endpoint could be the actual URL. Anyway, I'll see it as it come.

**Comment by andmarios** [comment]
Hey, late response, I know. I didn't merge this because it breaks the UI.
The UI uses the cluster name as part of the URL path. So, as example, under the current scheme, the first cluster is named connect-1 and its URL is:

    http://0.0.0.0:8001/#/cluster/connect-1

As your fix replaces the name with the Connect endpoint URL, the new URL becomes something like:

    http://0.0.0.0:8001/#/cluster/http://localhost:8083

Which isn't of course valid. I'll think of another solution. :)

**Comment by simplesteph** [comment]
@andmarios sounds good I'll close my PR. Looking forward to a fix :)

**Comment by andmarios** [comment]
I pushed a fix in the latest image (landoop/kafka-connect-ui:latest).

Now you can do something akin to 
```
-e "CONNECT_URL=http://connect.1.url;dev cluster,http://connect.2.url;production cluster"
```
Skipping the semicolons and names for an entry, will assign the default, auto-generated name.

Could you verify that it works for you when you find some time?

**Comment by simplesteph** [comment]
looks like it's working. Thanks!
