### ISSUE TITLE
Don't get the kafka-connect-ui running

### ISSUE THREAD

**Issue by AirTobe91** [Landoop/kafka-connect-ui#52]
Hello,
I'm trying to get the kafka-connect-ui running.
So I started the confluent services (running properly) and calling 
> sudo docker run --rm -it -p 8000:8000 -e "CONNECT_URL=http://127.0.0.1:8083" landoop/kafka-connect-ui

Then it is stating:

Enabling proxy because Connect doesn't send CORS headers yet and setting up clusters.

Activating privacy features... done.
http://0.0.0.0:8000

When I now try to look up in firefox on 127.0.0.1:8000 then it's stating:

Kafka Connect : /api/kafka-connect-1
Kafka Connect UI Version : 0.9.3
CONNECTIVITY ERROR

Could you maybe give me some help to get it running?
Thanks Tobias

**Comment by Martbob** [comment]
Got the same problem but using http://132.203.150.180:8083 (ip of my virtual box)

**Comment by andmarios** [comment]
It is a matter of (network) perspective. The Connect UI runs inside the docker container which has its own network space, so for it the address `http://127.0.0.1:8083` (localhost) is itself whilst for you is your own computer.

As Kafka Connect has recently added support for CORS, we should provide an option to not proxy its API. This would make things simpler in both your cases.

Until we do that, you have to provide an address that the Kafka Connect UI docker container can use to access Kafka Connect.

Which address is that? This is fairly difficult to say because of the myriad of configurations out there. A starting place would be to find the address of the container running connect and use that. For example:

     docker inspect [ID_of_connect_container] | grep IPAddress

Now, there are issues. Maybe your docker is setup so that it forbids containers talking to each other. Maybe you don't run connect in a container but directly on your operating system, so Connect UI would have to be able to access your operating system at its IP address (for example something like 192.168.1.10 if you are behind a router), etc.

If you give me more info on your setup, I may be able to help. I'll try to implement the no proxy option soon as well.

**Comment by vlad1777d** [comment]
As I understood, now not browser is sending request, but server.
So in **CONNECT_URL** instead of URL, by which browser can access **Kafka Connect containe**r, I need to specify URL, by which **Connect UI** server can access **Kafka Connect container**.

**Comment by andmarios** [comment]
We've added support to not proxy the Connect api.

For this you need a fairly recent Kafka Connect (0.11 or 1.0) and to add these options to it:

    access.control.allow.methods=GET,POST,PUT,DELETE,OPTIONS
    access.control.allow.origin=*.

Once you've done that, you can start `landoop/kafka-connect-ui` with `-e PROXY=false`.
This way instead of the container, your browser will access directly the kafka connect worker, which may solve the issue you experience.

**Comment by zhipcui** [comment]
@andmarios was right, but a little thing should be noticed.

```
access.control.allow.methods=GET,POST,PUT,DELETE,OPTIONS
access.control.allow.origin=*
```

**Comment by labhane** [comment]
@andmarios  and @zhipcui  

I am running kafka-connect-ui on windows without using docker setup. 
Although the access control allow settings were present in kafka-rest.properties and connect-standalone.properties but the kafka-connect-ui started working only after I updated the same settings in 
schema-registry.properties

**Comment by cricket007** [comment]
> need a fairly recent Kafka Connect (0.11 or 1.0)

Actually, 0.10+

https://issues.apache.org/jira/browse/KAFKA-3578

**Comment by AlexVPopov** [comment]
So this worked for me:
```
$ confluent start
$ docker run --rm -it -p 8000:8000 -e CONNECT_URL=host.docker.internal:8083 landoop/kafka-connect-ui
```

This trick is to use `host.docker.internal` instead of localhost, as inside the docker container `localhost` is the container itself and `host.docker.internal` is the Docker host, where confluent is running.

**Comment by scheung38** [comment]
@AlexVPopov thanks for sharing this hack, if the standard PostgreSQL and SpoolDir source connector is not shown how to use this tool?

**Comment by OneCricketeer** [comment]
@scheung38 this tool shows all connectors that are properly installed
